### ISSUE TITLE
About a Anomaly Detection error

### ISSUE THREAD

**Issue by MotorZ** [LeeDoYup/AnoGAN#10]
**Hi ! LeeDoYup**
First, Thank you for your share!

I use your code with my dataset to train DCGAN normally.After having trained DCGAN model, when I test with my data Using:
$ python main.py --dataset DATASET_NAME --input_height=108 --crop --anomaly_test

There always be a error:

Traceback (most recent call last):
  File "main.py", line 124, in <module>
    tf.app.run()
  File "/home/motorzhu/anaconda3/envs/py2/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 126, in run
    _sys.exit(main(argv))
  File "main.py", line 101, in main
    test_dir = FLAGS.test_dir)
  File "/home/motorzhu/Download/AnoGAN-master/model.py", line 67, in __init__
    imreadImg = imread(self.data[0])
IndexError: list index out of range

I do put my test data in "test_data",but it shows the model can‘t read the image,can you give me the right anomaly test command  ($ python main.py --dataset DATASET_NAME --input_height=108 --crop --anomaly_test) please? Thank you !

**Comment by lzzlxxlsz** [comment]
I have the same error,and have you solved this problem?
