### ISSUE TITLE
 Expect argument to be a string or int, found

### ISSUE THREAD

**Issue by uzl** [LeeDoYup/AnoGAN#12]
I am facing this problem. 

`$ python main.py --dataset cresco --train
Traceback (most recent call last):
  File "main.py", line 20, in <module>
    flags.DEFINE_integer("train_size", np.inf, "The size of train images [np.inf]")
  File "/home/uzzal/miniconda2/envs/tf_gpu_py2/lib/python2.7/site-packages/tensorflow/python/platform/flags.py", line 58, in wrapper
    return original_function(*args, **kwargs)
  File "/home/uzzal/miniconda2/envs/tf_gpu_py2/lib/python2.7/site-packages/absl/flags/_defines.py", line 315, in DEFINE_integer
    DEFINE(parser, name, default, help, flag_values, serializer, **args)
  File "/home/uzzal/miniconda2/envs/tf_gpu_py2/lib/python2.7/site-packages/absl/flags/_defines.py", line 81, in DEFINE
    DEFINE_flag(_flag.Flag(parser, serializer, name, default, help, **args),
  File "/home/uzzal/miniconda2/envs/tf_gpu_py2/lib/python2.7/site-packages/absl/flags/_flag.py", line 107, in __init__
    self._set_default(default)
  File "/home/uzzal/miniconda2/envs/tf_gpu_py2/lib/python2.7/site-packages/absl/flags/_flag.py", line 196, in _set_default    self.default = self._parse(value)
  File "/home/uzzal/miniconda2/envs/tf_gpu_py2/lib/python2.7/site-packages/absl/flags/_flag.py", line 169, in _parse
    'flag --%s=%s: %s' % (self.name, argument, e))
absl.flags._exceptions.IllegalFlagValueError: flag --train_size=inf: Expect argument to be a string or int, found <type 'float'>`

**Comment by ghuw** [comment]
@uzl I also had the same problem as you mentioned.
In my case, since `np.inf` type is `float`, you can change `flags.DEFINE_integer` of the following line:
https://github.com/LeeDoYup/AnoGAN/blob/7d03e01735254f26758f63fcf56bdbd36a49c053/main.py#L20
to `flags.DEFINE_float` . It works well after I changed that line.
