### ISSUE TITLE
downlaod

### ISSUE THREAD

**Issue by lzzlxxlsz** [LeeDoYup/AnoGAN#17]

**Comment by lzzlxxlsz** [comment]
**_hello,When I download the data, it always reports an error.Anymore , I  want to ask about the form of the mnist data?_**
there is the errors:
Traceback (most recent call last):
  File "D:\Anaconda\lib\site-packages\urllib3\contrib\pyopenssl.py", line 444, i
n wrap_socket
    cnx.do_handshake()
  File "D:\Anaconda\lib\site-packages\OpenSSL\SSL.py", line 1907, in do_handshak
e
    self._raise_ssl_error(self._ssl, result)
  File "D:\Anaconda\lib\site-packages\OpenSSL\SSL.py", line 1631, in _raise_ssl_
error
    raise SysCallError(errno, errorcode.get(errno))
OpenSSL.SSL.SysCallError: (10054, 'WSAECONNRESET')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Anaconda\lib\site-packages\urllib3\connectionpool.py", line 600, in u
rlopen
    chunked=chunked)
  File "D:\Anaconda\lib\site-packages\urllib3\connectionpool.py", line 343, in _
make_request
    self._validate_conn(conn)
  File "D:\Anaconda\lib\site-packages\urllib3\connectionpool.py", line 849, in _
validate_conn
    conn.connect()
  File "D:\Anaconda\lib\site-packages\urllib3\connection.py", line 356, in conne
ct
    ssl_context=context)
  File "D:\Anaconda\lib\site-packages\urllib3\util\ssl_.py", line 359, in ssl_wr
ap_socket
    return context.wrap_socket(sock, server_hostname=server_hostname)
  File "D:\Anaconda\lib\site-packages\urllib3\contrib\pyopenssl.py", line 450, i
n wrap_socket
    raise ssl.SSLError('bad handshake: %r' % e)
ssl.SSLError: ("bad handshake: SysCallError(10054, 'WSAECONNRESET')",)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Anaconda\lib\site-packages\requests\adapters.py", line 445, in send
    timeout=timeout
  File "D:\Anaconda\lib\site-packages\urllib3\connectionpool.py", line 638, in u
rlopen
    _stacktrace=sys.exc_info()[2])
  File "D:\Anaconda\lib\site-packages\urllib3\util\retry.py", line 398, in incre
ment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='docs.google.com', po
rt=443): Max retries exceeded with url: /uc?export=download&id=0B7EVK8r0v71pZjFT
YXZWM3FlRnM (Caused by SSLError(SSLError("bad handshake: SysCallError(10054, 'WS
AECONNRESET')")))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "download.py", line 152, in <module>
    download_celeb_a('./data')
  File "download.py", line 70, in download_celeb_a
    download_file_from_google_drive(drive_id, save_path)
  File "download.py", line 28, in download_file_from_google_drive
    response = session.get(URL, params={ 'id': id }, stream=True)
  File "D:\Anaconda\lib\site-packages\requests\sessions.py", line 525, in get
    return self.request('GET', url, **kwargs)
  File "D:\Anaconda\lib\site-packages\requests\sessions.py", line 512, in reques
t
    resp = self.send(prep, **send_kwargs)
  File "D:\Anaconda\lib\site-packages\requests\sessions.py", line 622, in send
    r = adapter.send(request, **kwargs)
  File "D:\Anaconda\lib\site-packages\requests\adapters.py", line 511, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='docs.google.com', port=4
43): Max retries exceeded with url: /uc?export=download&id=0B7EVK8r0v71pZjFTYXZW
M3FlRnM (Caused by SSLError(SSLError("bad handshake: SysCallError(10054, 'WSAECO
NNRESET')")))

**Comment by LeeDoYup** [comment]
I think it is connection error. which dataset are you download?

**Comment by lzzlxxlsz** [comment]
celebA
By the way ,the environment of your computer is cpu or gpu?,when I run the code ,It always has some errors.My conputer's environment is cpu.Thanks for your reply

**Comment by lzzlxxlsz** [comment]
is the system windows ok?

**Comment by lzzlxxlsz** [comment]
Sorry, if I finished this project,and I just run the download.py and then main.py,right? I have a little trouble in the training of DCGAN.Thanks for your reply

At 2019-03-07 17:08:43, "Doyup Lee" <notifications@github.com> wrote:


I think it is connection error. which dataset are you download?
