### ISSUE TITLE
AssertionError

### ISSUE THREAD

**Issue by mur909** [LeeDoYup/AnoGAN#42]
I used the celebA and met the trouble：

Epoch: [ 0] [  96/6331] time: 20.7979, d_loss: 2.24110365, g_loss: 0.32057661
Epoch: [ 0] [  97/6331] time: 20.9898, d_loss: 1.89617133, g_loss: 0.46526995
Epoch: [ 0] [  98/6331] time: 21.1837, d_loss: 1.54140878, g_loss: 0.72463155
Traceback (most recent call last):
  File "main.py", line 124, in <module>
    tf.app.run()
  File "/home/wangyun/anaconda3/envs/AnoGAN/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 126, in run
    _sys.exit(main(argv))
  File "main.py", line 106, in main
    dcgan.train(FLAGS)
  File "/home/wangyun/anaconda3/envs/AnoGAN/GAN/model.py", line 265, in train
    save_images(samples, image_manifold_size(samples.shape[0]),
  File "/home/wangyun/anaconda3/envs/AnoGAN/GAN/utils.py", line 197, in image_manifold_size
    assert manifold_h * manifold_w == num_images
AssertionError

Can you direct me？Thank you.

**Comment by mur909** [comment]
I have solved.
